In [1]:
import pandas as pd

In [2]:
#Dataframe topic
df=pd.DataFrame({'name':['A','B','C'],
              'age ':[10,12,11],
              'std' :[5,6,7]})
df['name']

0    A
1    B
2    C
Name: name, dtype: object

In [3]:
df[['name','std']]

  name  std
0    A    5
1    B    6
2    C    7

In [4]:
#create new column
df['address']=['vashi','belapur','sanpada']
df

  name  age   std  address
0    A    10    5    vashi
1    B    12    6  belapur
2    C    11    7  sanpada

In [5]:
#to create from start table
df2=pd.DataFrame()
df2['study_hr']=[1,2,3,4,5]
df2['makrs']=[40,29,30,130,55]
df2['marks']=[11,223,34,544,54]
df2

   study_hr  makrs  marks
0         1     40     11
1         2     29    223
2         3     30     34
3         4    130    544
4         5     55     54

In [6]:
df2.drop('makrs',axis=1)

   study_hr  marks
0         1     11
1         2    223
2         3     34
3         4    544
4         5     54

directly paste link on github

In [7]:
df=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Cleaning/dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [8]:
#by default 5 rows will show
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [9]:
df.tail() #by default it will show 5 from last records

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
df.sample(10) #bydefault 1

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9043,TXN_9438576,Cookie,1,1.0,1.0,Credit Card,In-store,2023-05-05
8672,TXN_6027798,Cookie,2,1.0,2.0,Digital Wallet,NaN,2023-05-26
8755,TXN_6963106,Sandwich,1,4.0,4.0,Cash,In-store,2023-06-01
6705,TXN_5679935,Coffee,2,2.0,4.0,Credit Card,NaN,2023-07-19
5972,TXN_3416466,Juice,2,3.0,6.0,Digital Wallet,NaN,2023-09-13
6398,TXN_5767392,Cake,5,3.0,15.0,Credit Card,NaN,2023-10-24
2186,TXN_1248436,Cake,4,3.0,12.0,Credit Card,Takeaway,2023-08-14
4278,TXN_5342900,Cake,5,3.0,15.0,Cash,NaN,2023-07-12
823,TXN_7896721,Cake,3,3.0,9.0,Credit Card,Takeaway,2023-04-22
8567,TXN_1357780,Tea,4,NaN,6.0,NaN,In-store,2023-10-23

In [11]:
df.info()  #basic information of datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [12]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [13]:
df.shape

(10000, 8)

In [14]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [15]:
df.describe(include=object)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_9226047,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [16]:
df2=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/flipkart_sales.csv')
df2

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [18]:
df2.describe(include=object)

        Order ID      Product Name     Category  Order Date Payment Method
count       1000              1000         1000        1000           1000
unique      1000                25            5         346              6
top     ORD01000  Educational Book  Electronics  2024-11-28            UPI
freq           1                64          217          10            176

In [19]:
df2.describe()

        Price (INR)  Quantity Sold  Total Sales (INR)  Customer Rating
count   1000.000000    1000.000000        1000.000000      1000.000000
mean   24520.258260       3.097000       75213.112740         3.011100
std    14187.611227       1.410525       59457.598352         1.145408
min      139.850000       1.000000         419.550000         1.000000
25%    12378.905000       2.000000       28581.765000         2.000000
50%    24650.015000       3.000000       57358.300000         3.100000
75%    35981.925000       4.000000      110618.595000         4.000000
max    49911.750000       5.000000      243903.900000         5.000000

In [20]:
df2.columns

Index(['Order ID', 'Product Name', 'Category', 'Price (INR)', 'Quantity Sold',
       'Total Sales (INR)', 'Order Date', 'Payment Method', 'Customer Rating'],
      dtype='object')

In [21]:
df2.shape

(1000, 9)

In [22]:
df2.describe(include='all')

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
count,1000,1000,1000,1000.000000,1000.000000,1000.000000,1000,1000,1000.000000
unique,1000,25,5,NaN,NaN,NaN,346,6,NaN
top,ORD01000,Educational Book,Electronics,NaN,NaN,NaN,2024-11-28,UPI,NaN
freq,1,64,217,NaN,NaN,NaN,10,176,NaN
mean,NaN,NaN,NaN,24520.258260,3.097000,75213.112740,NaN,NaN,3.011100
std,NaN,NaN,NaN,14187.611227,1.410525,59457.598352,NaN,NaN,1.145408
min,NaN,NaN,NaN,139.850000,1.000000,419.550000,NaN,NaN,1.000000
25%,NaN,NaN,NaN,12378.905000,2.000000,28581.765000,NaN,NaN,2.000000
50%,NaN,NaN,NaN,24650.015000,3.000000,57358.300000,NaN,NaN,3.100000
75%,NaN,NaN,NaN,35981.925000,4.000000,110618.595000,NaN,NaN,4.000000
max,NaN,NaN,NaN,49911.750000,5.000000,243903.900000,NaN,NaN,5.000000

In [23]:
df2.value_counts()

Order ID  Product Name      Category        Price (INR)  Quantity Sold  Total Sales (INR)  Order Date  Payment Method  Customer Rating
ORD01000  Table Lamp        Home & Kitchen  16698.12     4              66792.48           2024-03-26  Credit Card     1.6                1
ORD00001  Educational Book  Books           49069.56     2              98139.12           2024-09-12  Debit Card      3.5                1
ORD00002  Jeans             Clothing        12755.85     4              51023.40           2024-12-18  UPI             3.9                1
ORD00003  Face Cream        Beauty          11092.19     4              44368.76           2024-05-18  Debit Card      4.4                1
ORD00004  Smartwatch        Electronics     32657.81     1              32657.81           2024-11-08  Debit Card      3.2                1
                                                                                                                                         ..
ORD00013  Educational Book  Books           6670.82      5              33354.10           2024-02-23  COD             1.2                1
ORD00012  Lipstick          Beauty          48780.78     5              243903.90          2024-04-13  UPI             1.3                1
ORD00011  Perfume           Beauty          46409.57     5              232047.85          2025-02-08  UPI             2.3                1
ORD00010  Tablet            Electronics     26876.51     2              53753.02           2024-03-14  Debit Card      4.0                1
ORD00009  Jacket            Clothing        1987.39      2              3974.78            2025-01-18  Debit Card      2.6                1
Name: count, Length: 1000, dtype: int64

In [24]:
df['Location'].value_counts() #value with its count

Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [25]:
df2.sort_values(by='Total Sales (INR)') #by default ascending order

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
736,ORD00737,Hair Dryer,Beauty,139.85,3,419.55,2024-09-14,UPI,2.0
536,ORD00537,Educational Book,Books,492.53,1,492.53,2024-04-15,Credit Card,4.4
950,ORD00951,T-Shirt,Clothing,959.63,1,959.63,2024-11-21,Wallet,1.6
894,ORD00895,Tablet,Electronics,1002.29,1,1002.29,2025-01-08,UPI,1.4
522,ORD00523,Cookware Set,Home & Kitchen,218.58,5,1092.90,2024-04-20,Wallet,4.8
...,...,...,...,...,...,...,...,...,...
863,ORD00864,Self-Help Book,Books,47427.30,5,237136.50,2024-03-29,Wallet,4.0
924,ORD00925,Jeans,Clothing,47480.71,5,237403.55,2024-09-09,UPI,3.1
587,ORD00588,Jeans,Clothing,47535.79,5,237678.95,2024-02-15,Debit Card,1.8
683,ORD00684,Dress,Clothing,48130.60,5,240653.00,2024-11-23,UPI,4.0
11,ORD00012,Lipstick,Beauty,48780.78,5,243903.90,2024-04-13,UPI,1.3

In [26]:
#if we want descending order mentioned below
df2.sort_values(by='Total Sales (INR)',ascending=False)

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
11,ORD00012,Lipstick,Beauty,48780.78,5,243903.90,2024-04-13,UPI,1.3
683,ORD00684,Dress,Clothing,48130.60,5,240653.00,2024-11-23,UPI,4.0
587,ORD00588,Jeans,Clothing,47535.79,5,237678.95,2024-02-15,Debit Card,1.8
924,ORD00925,Jeans,Clothing,47480.71,5,237403.55,2024-09-09,UPI,3.1
863,ORD00864,Self-Help Book,Books,47427.30,5,237136.50,2024-03-29,Wallet,4.0
...,...,...,...,...,...,...,...,...,...
522,ORD00523,Cookware Set,Home & Kitchen,218.58,5,1092.90,2024-04-20,Wallet,4.8
894,ORD00895,Tablet,Electronics,1002.29,1,1002.29,2025-01-08,UPI,1.4
950,ORD00951,T-Shirt,Clothing,959.63,1,959.63,2024-11-21,Wallet,1.6
536,ORD00537,Educational Book,Books,492.53,1,492.53,2024-04-15,Credit Card,4.4
736,ORD00737,Hair Dryer,Beauty,139.85,3,419.55,2024-09-14,UPI,2.0

In [27]:
#Returns the number of missing (null) values in each column of your dataset
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [28]:
#Specific column we have to selected
#df
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [29]:
#total number of unique
df['Item'].nunique()   #no of unique values

10

In [30]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [31]:
df2

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1
...,...,...,...,...,...,...,...,...,...
995,ORD00996,Smartphone,Electronics,28995.81,3,86987.43,2025-01-13,COD,5.0
996,ORD00997,Perfume,Beauty,32799.51,2,65599.02,2024-12-18,Wallet,2.4
997,ORD00998,Face Cream,Beauty,40840.80,1,40840.80,2024-07-26,UPI,3.1
998,ORD00999,Cookware Set,Home & Kitchen,34741.79,4,138967.16,2024-10-02,Net Banking,3.2
999,ORD01000,Table Lamp,Home & Kitchen,16698.12,4,66792.48,2024-03-26,Credit Card,1.6

In [32]:
df3=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Cleaning/laptopData.csv')
df3

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [33]:
d={'Ram':'RAM(GB)','Weight':'Weight(kg)'}
df3.rename(columns=d,inplace=True)

In [34]:
df3

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [35]:
#to delete any column
#df3.drop(['Unnamed: 0','Company'],axis=1) #original dataframe will not affected

In [36]:
#df3 =df3.drop(['Unnamed: 0','Company'],axis=1, errors='ignore') #overide means original will also affected
#df3

In [37]:
#delete the particular data in row

In [38]:
df3.drop([0,1,2,5]) #original data will not affected

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
6,6.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,114017.6016
7,7.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,256GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,61735.5360
8,8.0,Asus,Ultrabook,14,Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,512GB SSD,Nvidia GeForce MX150,Windows 10,1.3kg,79653.6000
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [39]:
df3 #original data has not changed

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [40]:
df3.describe()

        Unnamed: 0          Price
count  1273.000000    1273.000000
mean    652.674784   59955.814073
std     376.493027   37332.251005
min       0.000000    9270.720000
25%     327.000000   31914.720000
50%     652.000000   52161.120000
75%     980.000000   79333.387200
max    1302.000000  324954.720000

In [41]:
df3.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
RAM(GB)             30
Memory              30
Gpu                 30
OpSys               30
Weight(kg)          30
Price               30
dtype: int64

In [42]:
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 108, 110],
    "Name": [
        "Aarav Sharma", "Riya Salunkhe", " Meera Sane ",
        "Rahul Patil", None, "Sneha Joshi", "Amit Shah", None,
        "Amit Shah", "Neha Desai"
    ],
    "Age": [25, 28, None, 32, 29, "Thirty", 27, 26, 27, None],
    "Gender": [
        "Male", "Female", "female", "MALE",
        None, "Female", "Male", "Female", "Male", "female"
    ],
    "Department": [
        "IT", "HR", "Finance", "IT", None,
        "HR", "Sales", "IT", "Sales", "Finance"
    ],
    "City": [
        "Mumbai", "Pune", "Mumbai", None,
        "Navi Mumbai", "mumbai", "Pune", "Mumbai",
        "Pune", " Pune "
    ],
    "Salary": [
        45000, 55000, None, 60000,
        48000, "52000", 47000, None,
        47000, 58000
    ],
    "Joining_Date": [
        "2023-01-15", "2022-06-20", None,
        "2021-03-10", "2023/05/12", "15-07-2022",
        "2022-08-30", None, "2022-08-30", "2020-12-01"
    ],
    "Performance_Score": [
        85, 92, None, 78, 88, 95, "90", None, 90, 72
    ]
}

df = pd.DataFrame(data)
df

,Emp_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Score
0,101,Aarav Sharma,25,Male,IT,Mumbai,45000,2023-01-15,85
1,102,Riya Salunkhe,28,Female,HR,Pune,55000,2022-06-20,92
2,103,Meera Sane,None,female,Finance,Mumbai,None,None,None
3,104,Rahul Patil,32,MALE,IT,None,60000,2021-03-10,78
4,105,None,29,None,None,Navi Mumbai,48000,2023/05/12,88
5,106,Sneha Joshi,Thirty,Female,HR,mumbai,52000,15-07-2022,95
6,107,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
7,108,None,26,Female,IT,Mumbai,None,None,None
8,108,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
9,110,Neha Desai,None,female,Finance,Pune,58000,2020-12-01,72

In [43]:
df.dropna(how='all')

,Emp_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Score
0,101,Aarav Sharma,25,Male,IT,Mumbai,45000,2023-01-15,85
1,102,Riya Salunkhe,28,Female,HR,Pune,55000,2022-06-20,92
2,103,Meera Sane,None,female,Finance,Mumbai,None,None,None
3,104,Rahul Patil,32,MALE,IT,None,60000,2021-03-10,78
4,105,None,29,None,None,Navi Mumbai,48000,2023/05/12,88
5,106,Sneha Joshi,Thirty,Female,HR,mumbai,52000,15-07-2022,95
6,107,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
7,108,None,26,Female,IT,Mumbai,None,None,None
8,108,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
9,110,Neha Desai,None,female,Finance,Pune,58000,2020-12-01,72

In [44]:
df

,Emp_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Score
0,101,Aarav Sharma,25,Male,IT,Mumbai,45000,2023-01-15,85
1,102,Riya Salunkhe,28,Female,HR,Pune,55000,2022-06-20,92
2,103,Meera Sane,None,female,Finance,Mumbai,None,None,None
3,104,Rahul Patil,32,MALE,IT,None,60000,2021-03-10,78
4,105,None,29,None,None,Navi Mumbai,48000,2023/05/12,88
5,106,Sneha Joshi,Thirty,Female,HR,mumbai,52000,15-07-2022,95
6,107,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
7,108,None,26,Female,IT,Mumbai,None,None,None
8,108,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
9,110,Neha Desai,None,female,Finance,Pune,58000,2020-12-01,72

In [45]:
df.dropna(subset=['Name','Department'])

,Emp_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Score
0,101,Aarav Sharma,25,Male,IT,Mumbai,45000,2023-01-15,85
1,102,Riya Salunkhe,28,Female,HR,Pune,55000,2022-06-20,92
2,103,Meera Sane,None,female,Finance,Mumbai,None,None,None
3,104,Rahul Patil,32,MALE,IT,None,60000,2021-03-10,78
5,106,Sneha Joshi,Thirty,Female,HR,mumbai,52000,15-07-2022,95
6,107,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
8,108,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
9,110,Neha Desai,None,female,Finance,Pune,58000,2020-12-01,72

In [46]:
df= df.dropna(subset=['Age','City']) #if any null value, it will delete the data from row

In [47]:
df= df.dropna(subset=['Age','City'])
df

,Emp_ID,Name,Age,Gender,Department,City,Salary,Joining_Date,Performance_Score
0,101,Aarav Sharma,25,Male,IT,Mumbai,45000,2023-01-15,85
1,102,Riya Salunkhe,28,Female,HR,Pune,55000,2022-06-20,92
4,105,None,29,None,None,Navi Mumbai,48000,2023/05/12,88
5,106,Sneha Joshi,Thirty,Female,HR,mumbai,52000,15-07-2022,95
6,107,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90
7,108,None,26,Female,IT,Mumbai,None,None,None
8,108,Amit Shah,27,Male,Sales,Pune,47000,2022-08-30,90

In [48]:
avg_sal=df3['Price'].mean()
df3['Price'].fillna(avg_sal)  #fillna is used to fill missing values (NaN) in a specific column of a DataFrame.

0        71378.6832
1        47895.5232
2        30636.0000
3       135195.3360
4        96095.8080
           ...
1298     33992.6400
1299     79866.7200
1300     12201.1200
1301     40705.9200
1302     19660.3200
Name: Price, Length: 1303, dtype: float64

In [49]:
#forward filling
df['Salary'].ffill() #forward filling mean from starting it will filled out the data if NULL values is there original data:10,null,20,30 then 10,10,20,30

0    45000
1    55000
4    48000
5    52000
6    47000
7    47000
8    47000
Name: Salary, dtype: object

In [50]:
#backward filling
df['Salary'].bfill()#backward filling means last data will filled out repeated if NULL values is there original data:10,null,20,30 then 10,20,20,30

0    45000
1    55000
4    48000
5    52000
6    47000
7    47000
8    47000
Name: Salary, dtype: object

In [51]:
df3

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 8
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             7 non-null      int64
 1   Name               5 non-null      object
 2   Age                7 non-null      object
 3   Gender             6 non-null      object
 4   Department         6 non-null      object
 5   City               7 non-null      object
 6   Salary             6 non-null      object
 7   Joining_Date       6 non-null      object
 8   Performance_Score  6 non-null      object
dtypes: int64(1), object(8)
memory usage: 560.0+ bytes

In [53]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [54]:
df3['RAM(GB)'].unique()

array(['8GB', '16GB', '4GB', nan, '2GB', '12GB', '64GB', '6GB', '32GB',
       '24GB', '1GB'], dtype=object)

In [55]:
s='66gb'            #removing the part
s.strip('gb')

'66'

In [56]:
df3['RAM(GB)']=df3['RAM(GB)'].str.strip('GB')

In [57]:
df3

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300.0,Lenovo,Notebook,14,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [58]:
df3['RAM(GB)'].astype('Int64')
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [59]:
df3['RAM(GB)'] = df3['RAM(GB)'].astype('Int64')  # storing the data using nullable integer type supporting NaNs
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: Int64(1), float64(2), object(9)
memory usage: 123.6+ KB

In [60]:
df3['Cpu'].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', nan, 'Intel Core i5 7300HQ 2.5GHz',
       'AMD E-Series E2-9000e 1.5GHz', 'Intel Core i5 1.6GHz',
       'Intel Core i7 8650U 1.9GHz', 'Intel Atom x5-Z8300 1.44GHz',
       'AMD E-Series E2-6110 1.5GHz', 'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'AMD A10-Series 9620P 2.5GHz', 'AMD E-Series 7110 1.8GHz',
       'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)

In [61]:
df3['Cpu'].str.split()

0                         [Intel, Core, i5, 2.3GHz]
1                         [Intel, Core, i5, 1.8GHz]
2                  [Intel, Core, i5, 7200U, 2.5GHz]
3                         [Intel, Core, i7, 2.7GHz]
4                         [Intel, Core, i5, 3.1GHz]
                           ...
1298               [Intel, Core, i7, 6500U, 2.5GHz]
1299               [Intel, Core, i7, 6500U, 2.5GHz]
1300    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
1301               [Intel, Core, i7, 6500U, 2.5GHz]
1302    [Intel, Celeron, Dual, Core, N3050, 1.6GHz]
Name: Cpu, Length: 1303, dtype: object

In [62]:
df3['Cpu'].str.split(expand=True)   #if i want intel

          0        1     2       3       4       5
0     Intel     Core    i5  2.3GHz    None    None
1     Intel     Core    i5  1.8GHz    None    None
2     Intel     Core    i5   7200U  2.5GHz    None
3     Intel     Core    i7  2.7GHz    None    None
4     Intel     Core    i5  3.1GHz    None    None
...     ...      ...   ...     ...     ...     ...
1298  Intel     Core    i7   6500U  2.5GHz    None
1299  Intel     Core    i7   6500U  2.5GHz    None
1300  Intel  Celeron  Dual    Core   N3050  1.6GHz
1301  Intel     Core    i7   6500U  2.5GHz    None
1302  Intel  Celeron  Dual    Core   N3050  1.6GHz

[1303 rows x 6 columns]

In [63]:
df3['Cpu'].str.split(expand=True)[0]

0       Intel
1       Intel
2       Intel
3       Intel
4       Intel
        ...
1298    Intel
1299    Intel
1300    Intel
1301    Intel
1302    Intel
Name: 0, Length: 1303, dtype: object

In [64]:
df3['CPUbrand']=df3['Cpu'].str.split(expand=True)[0] #list of CPU brand will be show

In [65]:
df3['CPUbrand'].unique()

array(['Intel', 'AMD', nan, 'Samsung'], dtype=object)

In [66]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(2), object(10)
memory usage: 133.7+ KB

In [67]:
df3['Inches'].unique()  #? has been there we shoul

array(['13.3', '15.6', '15.4', '14', '12', nan, '17.3', '13.5', '12.5',
       '13', '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '?', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [68]:
df3['Inches'].str.replace('?','0.0') #? is replace by 0.0

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298      14
1299    13.3
1300      14
1301    15.6
1302    15.6
Name: Inches, Length: 1303, dtype: object

In [69]:
df3['Inches']=df3['Inches'].str.replace('?','0.0')

In [70]:
df3['Inches'].unique()

array(['13.3', '15.6', '15.4', '14', '12', nan, '17.3', '13.5', '12.5',
       '13', '18.4', '13.9', '11.6', '25.6', '35.6', '12.3', '27.3', '24',
       '33.5', '0.0', '31.6', '17', '15', '14.1', '11.3', '10.1'],
      dtype=object)

In [71]:
df3['Inches'].astype(float)

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298    14.0
1299    13.3
1300    14.0
1301    15.6
1302    15.6
Name: Inches, Length: 1303, dtype: float64

In [72]:
df3['Inches']=df3['Inches'].astype(float)

In [73]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(3), object(9)
memory usage: 133.7+ KB

In [74]:
df3['Inches'].replace(0.0,df3['Inches'].median())

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298    14.0
1299    13.3
1300    14.0
1301    15.6
1302    15.6
Name: Inches, Length: 1303, dtype: float64

In [75]:
df3['Inches']=df3['Inches'].replace(0.0,df3['Inches'].median())

In [76]:
df3['Weight(kg)'].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', nan, '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg', '1.4kg',
       '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg', '1.63kg',
       '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg', '2.62kg',
       '1.38kg', '1.58kg', '1.85kg', '1.23kg', '2.16kg', '2.36kg',
       '7.2kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg', '2.56kg',
       '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg', '1.05kg', '5.4kg',
       '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg', '1.12kg',
       '3.49kg', '3.35kg', '2.23kg', '?', '2.9kg', '4.42kg', '2.69kg',
       '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg', '1.41kg',
       '4.14kg', '2.18kg', '2.24kg', '2.67kg', '4.1kg', '2.14kg',
       '1.36kg', '2.25kg', '2.15kg', '2.19kg', '2.54kg', '3.42kg',
       '5.8kg', '1.28kg', '2.33kg', '1.45kg', '2.79kg', '8.23kg',
       '1.26kg', '1.84kg', '0.0002kg', '2.6kg', '2.26kg', '3.25kg',
       '1.59kg', '1.13kg', '1.42kg', '1.78kg', '1.10kg', '1.15kg',
       '1.27kg', '1.43kg', '2.31kg', '1.16kg', '1.64kg', '2.17kg',
       '1.47kg', '3.78kg', '1.79kg', '0.91kg', '1.99kg', '4.33kg',
       '1.93kg', '1.87kg', '2.63kg', '3.4kg', '3.14kg', '1.94kg',
       '1.24kg', '4.6kg', '4.5kg', '8.4kg', '2.73kg', '1.39kg', '2.29kg',
       '2.59kg', '2.94kg', '11.1kg', '1.14kg', '3.8kg', '6.2kg', '3.31kg',
       '1.09kg', '3.21kg', '1.19kg', '1.98kg', '1.17kg', '4.36kg',
       '1.71kg', '2.32kg', '4.2kg', '1.55kg', '0.81kg', '1.18kg',
       '2.72kg', '1.31kg', '0.920kg', '3.74kg', '1.76kg', '1.54kg',
       '2.83kg', '2.07kg', '2.38kg', '3.58kg', '1.08kg', '2.20kg',
       '0.98kg', '2.75kg', '1.70kg', '2.99kg', '1.11kg', '2.09kg', '4kg',
       '3.0kg', '0.99kg', '0.69kg', '3.52kg', '2.591kg', '2.21kg',
       '3.3kg', '2.191kg', '2.34kg', '4.0kg'], dtype=object)

In [77]:
df3['Weight(kg)']=df3['Weight(kg)'].str.replace('?','0.0')

In [78]:
df3['Weight(kg)'].unique()

array(['1.37kg', '1.34kg', '1.86kg', '1.83kg', '2.1kg', '2.04kg', '1.3kg',
       '1.6kg', '2.2kg', '0.92kg', '1.22kg', nan, '2.5kg', '1.62kg',
       '1.91kg', '2.3kg', '1.35kg', '1.88kg', '1.89kg', '1.65kg',
       '2.71kg', '1.2kg', '1.44kg', '2.8kg', '2kg', '2.65kg', '2.77kg',
       '3.2kg', '1.49kg', '2.4kg', '2.13kg', '2.43kg', '1.7kg', '1.4kg',
       '1.8kg', '1.9kg', '3kg', '1.252kg', '2.7kg', '2.02kg', '1.63kg',
       '1.96kg', '1.21kg', '2.45kg', '1.25kg', '1.5kg', '2.62kg',
       '1.38kg', '1.58kg', '1.85kg', '1.23kg', '2.16kg', '2.36kg',
       '7.2kg', '2.05kg', '1.32kg', '1.75kg', '0.97kg', '2.56kg',
       '1.48kg', '1.74kg', '1.1kg', '1.56kg', '2.03kg', '1.05kg', '5.4kg',
       '4.4kg', '1.90kg', '1.29kg', '2.0kg', '1.95kg', '2.06kg', '1.12kg',
       '3.49kg', '3.35kg', '2.23kg', '0.0', '2.9kg', '4.42kg', '2.69kg',
       '2.37kg', '4.7kg', '3.6kg', '2.08kg', '4.3kg', '1.68kg', '1.41kg',
       '4.14kg', '2.18kg', '2.24kg', '2.67kg', '4.1kg', '2.14kg',
       '1.36kg', '2.25kg', '2.15kg', '2.19kg', '2.54kg', '3.42kg',
       '5.8kg', '1.28kg', '2.33kg', '1.45kg', '2.79kg', '8.23kg',
       '1.26kg', '1.84kg', '0.0002kg', '2.6kg', '2.26kg', '3.25kg',
       '1.59kg', '1.13kg', '1.42kg', '1.78kg', '1.10kg', '1.15kg',
       '1.27kg', '1.43kg', '2.31kg', '1.16kg', '1.64kg', '2.17kg',
       '1.47kg', '3.78kg', '1.79kg', '0.91kg', '1.99kg', '4.33kg',
       '1.93kg', '1.87kg', '2.63kg', '3.4kg', '3.14kg', '1.94kg',
       '1.24kg', '4.6kg', '4.5kg', '8.4kg', '2.73kg', '1.39kg', '2.29kg',
       '2.59kg', '2.94kg', '11.1kg', '1.14kg', '3.8kg', '6.2kg', '3.31kg',
       '1.09kg', '3.21kg', '1.19kg', '1.98kg', '1.17kg', '4.36kg',
       '1.71kg', '2.32kg', '4.2kg', '1.55kg', '0.81kg', '1.18kg',
       '2.72kg', '1.31kg', '0.920kg', '3.74kg', '1.76kg', '1.54kg',
       '2.83kg', '2.07kg', '2.38kg', '3.58kg', '1.08kg', '2.20kg',
       '0.98kg', '2.75kg', '1.70kg', '2.99kg', '1.11kg', '2.09kg', '4kg',
       '3.0kg', '0.99kg', '0.69kg', '3.52kg', '2.591kg', '2.21kg',
       '3.3kg', '2.191kg', '2.34kg', '4.0kg'], dtype=object)

In [79]:
df3['Weight(kg)'].str.strip('kg')

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298     1.8
1299     1.3
1300     1.5
1301    2.19
1302     2.2
Name: Weight(kg), Length: 1303, dtype: object

In [80]:
# df3['Weight(kg)']=df3['Weight(kg)'].str.strip('kg') # This line is no longer needed as the column is already float #to cut the kg word

In [81]:
#df3['Weight(kg)']=df3['Weight(kg)'].astype(float)

In [82]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(3), object(9)
memory usage: 133.7+ KB

In [83]:
#df3['Weight(kg)'].replace(0.0, df3['Weight(kg)'].median())

In [84]:
#df3['Weight(kg)'] =df3['Weight(kg)'].replace(0.0, df3['Weight(kg)'].median())

In [85]:
df2.head()

,Order ID,Product Name,Category,Price (INR),Quantity Sold,Total Sales (INR),Order Date,Payment Method,Customer Rating
0,ORD00001,Educational Book,Books,49069.56,2,98139.12,2024-09-12,Debit Card,3.5
1,ORD00002,Jeans,Clothing,12755.85,4,51023.40,2024-12-18,UPI,3.9
2,ORD00003,Face Cream,Beauty,11092.19,4,44368.76,2024-05-18,Debit Card,4.4
3,ORD00004,Smartwatch,Electronics,32657.81,1,32657.81,2024-11-08,Debit Card,3.2
4,ORD00005,Cookware Set,Home & Kitchen,26590.08,3,79770.24,2024-12-27,UPI,3.1

In [86]:
df3.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price,CPUbrand
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel

In [87]:
#rearrange

In [88]:
df3['Weight(kg)']=df3['Weight(kg)'].str.strip('kg')  #remove unwanted characters, especially spaces from the beginning and end of a string.

In [89]:
df3

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,RAM(GB),Memory,Gpu,OpSys,Weight(kg),Price,CPUbrand
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,Intel
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232,Intel
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000,Intel
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360,Intel
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298.0,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4,128GB SSD,Intel HD Graphics 520,Windows 10,1.8,33992.6400,Intel
1299,1299.0,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16,512GB SSD,Intel HD Graphics 520,Windows 10,1.3,79866.7200,Intel
1300,1300.0,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5,12201.1200,Intel
1301,1301.0,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200,Intel
1302,1302.0,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4,500GB HDD,Intel HD Graphics,Windows 10,2.2,19660.3200,Intel

In [90]:
df3['Weight(kg)']=df3['Weight(kg)'].replace('?','0.0')   # removing null ?

In [91]:
df3['Weight(kg)'].unique()

array(['1.37', '1.34', '1.86', '1.83', '2.1', '2.04', '1.3', '1.6', '2.2',
       '0.92', '1.22', nan, '2.5', '1.62', '1.91', '2.3', '1.35', '1.88',
       '1.89', '1.65', '2.71', '1.2', '1.44', '2.8', '2', '2.65', '2.77',
       '3.2', '1.49', '2.4', '2.13', '2.43', '1.7', '1.4', '1.8', '1.9',
       '3', '1.252', '2.7', '2.02', '1.63', '1.96', '1.21', '2.45',
       '1.25', '1.5', '2.62', '1.38', '1.58', '1.85', '1.23', '2.16',
       '2.36', '7.2', '2.05', '1.32', '1.75', '0.97', '2.56', '1.48',
       '1.74', '1.1', '1.56', '2.03', '1.05', '5.4', '4.4', '1.90',
       '1.29', '2.0', '1.95', '2.06', '1.12', '3.49', '3.35', '2.23',
       '0.0', '2.9', '4.42', '2.69', '2.37', '4.7', '3.6', '2.08', '4.3',
       '1.68', '1.41', '4.14', '2.18', '2.24', '2.67', '4.1', '2.14',
       '1.36', '2.25', '2.15', '2.19', '2.54', '3.42', '5.8', '1.28',
       '2.33', '1.45', '2.79', '8.23', '1.26', '1.84', '0.0002', '2.6',
       '2.26', '3.25', '1.59', '1.13', '1.42', '1.78', '1.10', '1.15',
       '1.27', '1.43', '2.31', '1.16', '1.64', '2.17', '1.47', '3.78',
       '1.79', '0.91', '1.99', '4.33', '1.93', '1.87', '2.63', '3.4',
       '3.14', '1.94', '1.24', '4.6', '4.5', '8.4', '2.73', '1.39',
       '2.29', '2.59', '2.94', '11.1', '1.14', '3.8', '6.2', '3.31',
       '1.09', '3.21', '1.19', '1.98', '1.17', '4.36', '1.71', '2.32',
       '4.2', '1.55', '0.81', '1.18', '2.72', '1.31', '0.920', '3.74',
       '1.76', '1.54', '2.83', '2.07', '2.38', '3.58', '1.08', '2.20',
       '0.98', '2.75', '1.70', '2.99', '1.11', '2.09', '4', '3.0', '0.99',
       '0.69', '3.52', '2.591', '2.21', '3.3', '2.191', '2.34', '4.0'],
      dtype=object)

In [92]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   object
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(3), object(9)
memory usage: 133.7+ KB

In [93]:
# make weight(kg) into float datatype

In [94]:
df3['Weight(kg)']=df3['Weight(kg)'].astype('float')

In [95]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1273 non-null   float64
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(4), object(8)
memory usage: 133.7+ KB

In [96]:
import numpy as np

In [97]:
df3['Weight(kg)']=df3['Weight(kg)'].replace(0.0,np.median(df3['Weight(kg)']))

In [98]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   float64
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   RAM(GB)           1273 non-null   Int64
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight(kg)        1272 non-null   float64
 11  Price             1273 non-null   float64
 12  CPUbrand          1273 non-null   object
dtypes: Int64(1), float64(4), object(8)
memory usage: 133.7+ KB